"""
Django settings for codeteki_site project.

Generated by 'django-admin startproject' using Django 4.2.7.

This configuration is tailored for the Codeteki single-server stack where
React builds live inside ``frontend/dist`` and are served by Django.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR.parent / "frontend"
FRONTEND_BUILD = FRONTEND_DIR / "build"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-^=9cz#wh44c(m+c7c*f-68^pyn$2nayx&4308ui(6b_48-!w3r",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# Increase limits for large SEO keyword uploads (1000s of keywords)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000  # Default is 1000
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1"
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'unfold',  # Modern Tailwind admin theme - must be before django.contrib.admin
    'unfold.contrib.filters',  # Enhanced filters
    'unfold.contrib.forms',  # Enhanced form widgets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Dynamic sitemap generation
    'ckeditor',  # Rich text editor
    'django_celery_results',  # Store Celery task results in database
    'django_celery_beat',  # Periodic task scheduler
    'core',
    'crm',  # CRM with AI-powered outreach
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codeteki_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
            FRONTEND_BUILD,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codeteki_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Cache configuration for API response caching
# Uses local memory cache (upgrade to Redis/Memcached for production)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'codeteki-cache',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Cache timeouts for different content types (in seconds)
CACHE_TIMEOUT_SHORT = 60  # 1 minute - for dynamic content
CACHE_TIMEOUT_MEDIUM = 300  # 5 minutes - for semi-static content
CACHE_TIMEOUT_LONG = 900  # 15 minutes - for mostly static content


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = []

# Include frontend build root for public assets (images, manifest, etc.)
# and build/static for JS/CSS bundles
for path in [BASE_DIR / "static", FRONTEND_BUILD, FRONTEND_BUILD / "static"]:
    if path.exists():
        STATICFILES_DIRS.append(path)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise cache settings - cache static files for 1 year (files have hashed names)
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds

# Use Django's static file finders in development so React build assets load
if DEBUG:
    WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    if origin.strip()
]

# Media files (user uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor Configuration
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# AI Content configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_SEO_MODEL = os.getenv("OPENAI_SEO_MODEL", "gpt-4o-mini")

# Google APIs for SEO Engine
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv(
    "GOOGLE_SERVICE_ACCOUNT_FILE",
    str(BASE_DIR / "credentials" / "codeteki-seo-engine-c4aa28232d6d.json")
)
GOOGLE_SEARCH_CONSOLE_PROPERTY = os.getenv("GOOGLE_SEARCH_CONSOLE_PROPERTY", "https://www.codeteki.au/")

# Site URL for SEO audits
SITE_URL = os.getenv("SITE_URL", "https://codeteki.au")

# Celery Configuration
# Redis as message broker (install Redis on server: apt install redis-server)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"  # Store results in Django database
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task

# Celery Beat Schedule for CRM tasks
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'crm-process-pending-deals': {
        'task': 'crm.tasks.process_pending_deals',
        'schedule': crontab(minute=0),  # Every hour
    },
    'crm-send-scheduled-emails': {
        'task': 'crm.tasks.send_scheduled_emails',
        'schedule': crontab(minute='*/15'),  # Every 15 minutes
    },
    'crm-check-email-replies': {
        'task': 'crm.tasks.check_email_replies',
        'schedule': crontab(minute='*/30'),  # Every 30 minutes
    },
    'crm-daily-ai-review': {
        'task': 'crm.tasks.daily_ai_review',
        'schedule': crontab(hour=9, minute=0),  # 9 AM daily
    },
}

# Zoho Mail API Configuration (for CRM email outreach)
ZOHO_CLIENT_ID = os.getenv("ZOHO_CLIENT_ID", "")
ZOHO_CLIENT_SECRET = os.getenv("ZOHO_CLIENT_SECRET", "")
ZOHO_REFRESH_TOKEN = os.getenv("ZOHO_REFRESH_TOKEN", "")
ZOHO_ACCOUNT_ID = os.getenv("ZOHO_ACCOUNT_ID", "")
ZOHO_FROM_EMAIL = os.getenv("ZOHO_FROM_EMAIL", "outreach@codeteki.au")
ZOHO_API_DOMAIN = os.getenv("ZOHO_API_DOMAIN", "zoho.com")  # Use zoho.com.au for Australia

# Django Unfold Configuration
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Codeteki CMS",
    "SITE_HEADER": "Codeteki",
    "SITE_SUBHEADER": "Content Management System",
    "SITE_DROPDOWN": [
        {
            "icon": "public",
            "title": "View Live Site",
            "link": "/",
        },
    ],
    # Logo
    "SITE_LOGO": {
        "light": lambda request: static("images/logo.png"),
        "dark": lambda request: static("images/logo-dark.png"),
    },
    "SITE_SYMBOL": "rocket_launch",  # Material icon
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: static("favicon.ico"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "core.utils.environment_callback",
    "DASHBOARD_CALLBACK": "core.utils.dashboard_callback",
    "LOGIN": {
        "image": lambda request: static("images/login-bg.jpg"),
    },
    "STYLES": [
        lambda request: static("css/admin-custom.css"),
    ],
    "SCRIPTS": [
        lambda request: static("admin/js/seo-loading.js"),
    ],
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "75 85 99",
            "default-dark": "209 213 219",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        "primary": {
            "50": "255 251 235",
            "100": "254 243 199",
            "200": "253 230 138",
            "300": "252 211 77",
            "400": "251 191 36",
            "500": "245 158 11",  # Codeteki yellow/amber
            "600": "217 119 6",
            "700": "180 83 9",
            "800": "146 64 14",
            "900": "120 53 15",
            "950": "69 26 3",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "au": "🇦🇺",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            # ============================================
            # HOME PAGE SECTIONS - Matching Frontend Order
            # ============================================
            {
                "title": "Home Page Sections",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "1. Hero Section",
                        "icon": "flag",
                        "link": reverse_lazy("admin:core_herosection_changelist"),
                        "badge": "core.utils.home_page_badge",
                    },
                    {
                        "title": "2. Business Impact",
                        "icon": "trending_up",
                        "link": reverse_lazy("admin:core_businessimpactsection_changelist"),
                    },
                    {
                        "title": "3. Services",
                        "icon": "build",
                        "link": reverse_lazy("admin:core_service_changelist"),
                    },
                    {
                        "title": "4. AI Tools Gallery",
                        "icon": "smart_toy",
                        "link": reverse_lazy("admin:core_aitool_changelist"),
                    },
                    {
                        "title": "5. ROI Calculator",
                        "icon": "calculate",
                        "link": reverse_lazy("admin:core_roicalculatorsection_changelist"),
                    },
                    {
                        "title": "6. Why Choose Us",
                        "icon": "verified",
                        "link": reverse_lazy("admin:core_whychoosesection_changelist"),
                    },
                    {
                        "title": "7. Contact Form",
                        "icon": "contact_mail",
                        "link": reverse_lazy("admin:core_contactmethod_changelist"),
                    },
                ],
            },
            # ============================================
            # SERVICES PAGE
            # ============================================
            {
                "title": "Services Page",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Services List",
                        "icon": "build",
                        "link": reverse_lazy("admin:core_service_changelist"),
                    },
                    {
                        "title": "Service Process Steps",
                        "icon": "timeline",
                        "link": reverse_lazy("admin:core_serviceprocessstep_changelist"),
                    },
                    {
                        "title": "Pricing Plans",
                        "icon": "payments",
                        "link": reverse_lazy("admin:core_pricingplan_changelist"),
                    },
                ],
            },
            # ============================================
            # CONTACT PAGE
            # ============================================
            {
                "title": "Contact Page",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Contact Methods",
                        "icon": "contact_mail",
                        "link": reverse_lazy("admin:core_contactmethod_changelist"),
                    },
                    {
                        "title": "Contact Inquiries",
                        "icon": "inbox",
                        "link": reverse_lazy("admin:core_contactinquiry_changelist"),
                    },
                ],
            },
            # ============================================
            # FAQ PAGE
            # ============================================
            {
                "title": "FAQ Page",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "FAQ Page Header",
                        "icon": "title",
                        "link": reverse_lazy("admin:core_faqpagesection_changelist"),
                    },
                    {
                        "title": "FAQ Categories",
                        "icon": "help",
                        "link": reverse_lazy("admin:core_faqcategory_changelist"),
                    },
                ],
            },
            # ============================================
            # OTHER PAGES
            # ============================================
            {
                "title": "Other Pages",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Demos/Showcases",
                        "icon": "movie",
                        "link": reverse_lazy("admin:core_demoshowcase_changelist"),
                    },
                    {
                        "title": "Testimonials",
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:core_testimonial_changelist"),
                    },
                    {
                        "title": "AI Tools Gallery",
                        "icon": "smart_toy",
                        "link": reverse_lazy("admin:core_aitool_changelist"),
                    },
                ],
            },
            # ============================================
            # BLOG & CONTENT
            # ============================================
            {
                "title": "Blog & Content",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "AI Blog Builder",
                        "icon": "auto_awesome",
                        "link": reverse_lazy("admin:core_bloggenerationjob_changelist"),
                    },
                    {
                        "title": "Blog Posts",
                        "icon": "article",
                        "link": reverse_lazy("admin:core_blogpost_changelist"),
                    },
                    {
                        "title": "Blog Categories",
                        "icon": "category",
                        "link": reverse_lazy("admin:core_blogcategory_changelist"),
                    },
                    {
                        "title": "Knowledge Base",
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:core_knowledgearticle_changelist"),
                    },
                ],
            },
            {
                "title": "SEO Management",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Page SEO Tags",
                        "icon": "sell",
                        "link": reverse_lazy("admin:core_pageseo_changelist"),
                    },
                    {
                        "title": "SEO Uploads",
                        "icon": "upload_file",
                        "link": reverse_lazy("admin:core_seodataupload_changelist"),
                    },
                    {
                        "title": "Keywords",
                        "icon": "key",
                        "link": reverse_lazy("admin:core_seokeyword_changelist"),
                    },
                    {
                        "title": "Keyword Clusters",
                        "icon": "hub",
                        "link": reverse_lazy("admin:core_seokeywordcluster_changelist"),
                    },
                    {
                        "title": "AI Recommendations",
                        "icon": "lightbulb",
                        "link": reverse_lazy("admin:core_aiseorecommendation_changelist"),
                    },
                ],
            },
            {
                "title": "SEO Engine",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Site Audits",
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:core_siteaudit_changelist"),
                        "badge": "core.utils.audit_badge",
                    },
                    {
                        "title": "AI Analysis",
                        "icon": "smart_toy",
                        "link": reverse_lazy("admin:core_aianalysisreport_changelist"),
                    },
                    {
                        "title": "Page Audits",
                        "icon": "description",
                        "link": reverse_lazy("admin:core_pageaudit_changelist"),
                    },
                    {
                        "title": "Audit Issues",
                        "icon": "warning",
                        "link": reverse_lazy("admin:core_auditissue_changelist"),
                    },
                    {
                        "title": "PageSpeed Results",
                        "icon": "speed",
                        "link": reverse_lazy("admin:core_pagespeedresult_changelist"),
                    },
                    {
                        "title": "Search Console Data",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:core_searchconsoledata_changelist"),
                    },
                    {
                        "title": "Search Console Sync",
                        "icon": "sync",
                        "link": reverse_lazy("admin:core_searchconsolesync_changelist"),
                    },
                    {
                        "title": "Keyword Rankings",
                        "icon": "trending_up",
                        "link": reverse_lazy("admin:core_keywordranking_changelist"),
                    },
                    {
                        "title": "Competitors",
                        "icon": "business",
                        "link": reverse_lazy("admin:core_competitorprofile_changelist"),
                    },
                    {
                        "title": "SEO Recommendations",
                        "icon": "tips_and_updates",
                        "link": reverse_lazy("admin:core_seorecommendation_changelist"),
                    },
                    {
                        "title": "Scheduled Audits",
                        "icon": "schedule",
                        "link": reverse_lazy("admin:core_scheduledaudit_changelist"),
                    },
                    {
                        "title": "Change Log",
                        "icon": "history",
                        "link": reverse_lazy("admin:core_seochangelog_changelist"),
                    },
                ],
            },
            # ============================================
            # CHATBOT LEADS
            # ============================================
            {
                "title": "Chatbot Leads",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Chat Leads",
                        "icon": "person_add",
                        "link": reverse_lazy("admin:core_chatlead_changelist"),
                        "badge": "core.utils.leads_badge",
                    },
                    {
                        "title": "Conversations",
                        "icon": "chat",
                        "link": reverse_lazy("admin:core_chatconversation_changelist"),
                    },
                    {
                        "title": "Contact Inquiries",
                        "icon": "inbox",
                        "link": reverse_lazy("admin:core_contactinquiry_changelist"),
                    },
                    {
                        "title": "Chatbot Settings",
                        "icon": "smart_toy",
                        "link": reverse_lazy("admin:core_chatbotsettings_changelist"),
                    },
                ],
            },
            {
                "title": "Site Configuration",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Site Settings",
                        "icon": "tune",
                        "link": reverse_lazy("admin:core_sitesettings_changelist"),
                    },
                    {
                        "title": "Navigation Menus",
                        "icon": "menu",
                        "link": reverse_lazy("admin:core_navigationmenu_changelist"),
                    },
                    {
                        "title": "Footer",
                        "icon": "view_agenda",
                        "link": reverse_lazy("admin:core_footersection_changelist"),
                    },
                    {
                        "title": "CTA Sections",
                        "icon": "campaign",
                        "link": reverse_lazy("admin:core_ctasection_changelist"),
                    },
                    {
                        "title": "Statistics",
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:core_statmetric_changelist"),
                    },
                ],
            },
            # ============================================
            # CRM & Outreach (Merged)
            # ============================================
            {
                "title": "CRM & Outreach",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Pipeline Board",
                        "icon": "view_kanban",
                        "link": "/admin/crm/dashboard/",
                    },
                    {
                        "title": "Codeteki Contacts",
                        "icon": "person",
                        "link": reverse_lazy("admin:crm_codetekicontact_changelist"),
                    },
                    {
                        "title": "Desi Firms Contacts",
                        "icon": "people",
                        "link": reverse_lazy("admin:crm_desifirmscontact_changelist"),
                    },
                    {
                        "title": "All Contacts",
                        "icon": "contacts",
                        "link": reverse_lazy("admin:crm_contact_changelist"),
                    },
                    {
                        "title": "Email Composer",
                        "icon": "edit_note",
                        "link": reverse_lazy("admin:crm_emaildraft_changelist"),
                    },
                    {
                        "title": "Deals",
                        "icon": "handshake",
                        "link": reverse_lazy("admin:crm_deal_changelist"),
                    },
                    {
                        "title": "Import Contacts",
                        "icon": "upload_file",
                        "link": reverse_lazy("admin:crm_contactimport_changelist"),
                    },
                    {
                        "title": "Brands",
                        "icon": "business",
                        "link": reverse_lazy("admin:crm_brand_changelist"),
                    },
                    {
                        "title": "Pipeline Settings",
                        "icon": "settings",
                        "link": reverse_lazy("admin:crm_pipeline_changelist"),
                    },
                    {
                        "title": "Backlinks",
                        "icon": "link",
                        "link": reverse_lazy("admin:crm_backlinkopportunity_changelist"),
                    },
                ],
            },
            # ============================================
            # Celery Task Management
            # ============================================
            {
                "title": "Background Tasks",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Periodic Tasks",
                        "icon": "schedule",
                        "link": reverse_lazy("admin:django_celery_beat_periodictask_changelist"),
                    },
                    {
                        "title": "Task Results",
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:django_celery_results_taskresult_changelist"),
                    },
                    {
                        "title": "Interval Schedules",
                        "icon": "timer",
                        "link": reverse_lazy("admin:django_celery_beat_intervalschedule_changelist"),
                    },
                    {
                        "title": "Crontab Schedules",
                        "icon": "event_repeat",
                        "link": reverse_lazy("admin:django_celery_beat_crontabschedule_changelist"),
                    },
                ],
            },
            {
                "title": "Users & Auth",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
    # TABS removed - using sidebar navigation only for consistent experience
}
