"""
Django settings for codeteki_site project.

Generated by 'django-admin startproject' using Django 4.2.7.

This configuration is tailored for the Codeteki single-server stack where
React builds live inside ``frontend/dist`` and are served by Django.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR.parent / "frontend"
FRONTEND_BUILD = FRONTEND_DIR / "build"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-^=9cz#wh44c(m+c7c*f-68^pyn$2nayx&4308ui(6b_48-!w3r",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1"
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Modern admin theme - must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',  # Rich text editor
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codeteki_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
            FRONTEND_BUILD,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codeteki_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = []

# Include frontend build root for public assets (images, manifest, etc.)
# and build/static for JS/CSS bundles
for path in [BASE_DIR / "static", FRONTEND_BUILD, FRONTEND_BUILD / "static"]:
    if path.exists():
        STATICFILES_DIRS.append(path)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Use Django's static file finders in development so React build assets load
if DEBUG:
    WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    if origin.strip()
]

# Media files (user uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor Configuration
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# AI Content configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_SEO_MODEL = os.getenv("OPENAI_SEO_MODEL", "gpt-4o-mini")

# Django Jazzmin Configuration
JAZZMIN_SETTINGS = {
    # Title on the login screen & brand name
    "site_title": "Codeteki Admin",
    "site_header": "Codeteki",
    "site_brand": "Codeteki CMS",
    "site_logo": None,  # Can add logo path here if needed
    "login_logo": None,
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to Codeteki Admin Panel",

    # Copyright on the footer
    "copyright": "Codeteki Digital Services",

    # Search model from navbar
    "search_model": ["core.Service", "core.FAQItem"],

    # User menu
    "user_avatar": None,

    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],

    #############
    # User Menu #
    #############
    "usermenu_links": [
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Custom icons for models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.HeroSection": "fas fa-home",
        "core.Service": "fas fa-cogs",
        "core.BusinessImpactSection": "fas fa-chart-line",
        "core.FAQCategory": "fas fa-question-circle",
        "core.ContactMethod": "fas fa-envelope",
        "core.ROICalculatorSection": "fas fa-calculator",
        "core.AIToolsSection": "fas fa-robot",
        "core.AITool": "fas fa-magic",
        "core.WhyChooseSection": "fas fa-star",
        "core.FooterSection": "fas fa-info-circle",
        "core.SiteSettings": "fas fa-sliders-h",
        "core.PageSEO": "fas fa-search",
        "core.SEODataUpload": "fas fa-file-upload",
        "core.SEOKeyword": "fas fa-key",
        "core.SEOKeywordCluster": "fas fa-project-diagram",
        "core.AISEORecommendation": "fas fa-microchip",
        "core.ChatbotSettings": "fas fa-robot",
        "core.KnowledgeCategory": "fas fa-folder-tree",
        "core.KnowledgeArticle": "fas fa-book-open",
        "core.ChatConversation": "fas fa-comments",
        "core.ChatLead": "fas fa-user-plus",
        "core.Testimonial": "fas fa-quote-right",
        "core.CTASection": "fas fa-bullhorn",
        "core.DemoShowcase": "fas fa-image",
        "core.PricingPlan": "fas fa-tags",
        "core.StatMetric": "fas fa-chart-bar",
        "core.NavigationMenu": "fas fa-bars",
        "core.NavigationItem": "fas fa-link",
        "core.BlogPost": "fas fa-newspaper",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},

    # Theme
    "theme": "flatly",  # Options: cerulean, cosmo, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, yeti
}

# UI Tweaks for colors
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "#f9cb07",  # Your brand yellow
    "accent": "accent-warning",
    "navbar": "navbar-warning navbar-dark",  # Use warning for yellow
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",  # Dark sidebar with yellow accents
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
