# Generated by Django 4.2.7 on 2026-01-15 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_add_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prompt_type', models.CharField(choices=[('email_compose', 'Email Compose'), ('email_followup', 'Email Follow-up'), ('reply_classify', 'Reply Classify'), ('lead_score', 'Lead Score'), ('deal_analyze', 'Deal Analyze'), ('backlink_pitch', 'Backlink Pitch')], max_length=30)),
                ('prompt_text', models.TextField()),
                ('system_prompt', models.TextField(blank=True, help_text='Optional system prompt override')),
                ('variables', models.JSONField(blank=True, default=list, help_text="Expected variables: ['contact_name', 'company', 'website']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Template',
                'verbose_name_plural': 'AI Prompt Templates',
                'ordering': ['prompt_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('domain_authority', models.IntegerField(blank=True, help_text='Domain Authority score 0-100', null=True)),
                ('contact_type', models.CharField(choices=[('lead', 'Lead'), ('backlink_target', 'Backlink Target'), ('partner', 'Partner')], default='lead', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Where this contact came from', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Flexible tagging')),
                ('ai_score', models.IntegerField(default=0, help_text='AI lead scoring 0-100')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contact', to='core.chatlead')),
                ('contact_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contact', to='core.contactinquiry')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('paused', 'Paused')], default='active', max_length=20)),
                ('ai_notes', models.TextField(blank=True, help_text='AI observations and analysis')),
                ('next_action_date', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emails_sent', models.IntegerField(default=0)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Sequence',
                'verbose_name_plural': 'Email Sequences',
                'ordering': ['pipeline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pipeline_type', models.CharField(choices=[('sales', 'Sales'), ('backlink', 'Backlink Outreach'), ('partnership', 'Partnership')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('delay_days', models.IntegerField(default=0, help_text='Days after previous step')),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('ai_personalize', models.BooleanField(default=True, help_text='AI should personalize this email')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.emailsequence')),
            ],
            options={
                'verbose_name': 'Sequence Step',
                'verbose_name_plural': 'Sequence Steps',
                'ordering': ['sequence', 'order'],
                'unique_together': {('sequence', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('auto_actions', models.JSONField(blank=True, default=dict, help_text="AI triggers: {action: 'send_email', template: 'initial_outreach'}")),
                ('days_until_followup', models.IntegerField(default=3, help_text='Days to wait before follow-up action')),
                ('is_terminal', models.BooleanField(default=False, help_text='Marks end states like Won/Lost')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Stage',
                'verbose_name_plural': 'Pipeline Stages',
                'ordering': ['pipeline', 'order'],
                'unique_together': {('pipeline', 'order')},
            },
        ),
        migrations.AddField(
            model_name='emailsequence',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sequences', to='crm.pipeline'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('from_email', models.EmailField(default='outreach@codeteki.au', max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('replied', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_content', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('zoho_message_id', models.CharField(blank=True, max_length=255)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='crm.deal')),
                ('sequence_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='crm.sequencestep')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('stage_change', 'Stage Changed'), ('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_replied', 'Email Replied'), ('note_added', 'Note Added'), ('ai_action', 'AI Action'), ('status_change', 'Status Changed')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
            ],
            options={
                'verbose_name': 'Deal Activity',
                'verbose_name_plural': 'Deal Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.pipeline'),
        ),
        migrations.CreateModel(
            name='BacklinkOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(help_text='Target page URL for backlink')),
                ('target_domain', models.CharField(max_length=255)),
                ('domain_authority', models.IntegerField(default=0, help_text='DA score 0-100')),
                ('relevance_score', models.IntegerField(default=0, help_text='Relevance to our content 0-100')),
                ('our_content_url', models.URLField(help_text='Our content URL to promote')),
                ('anchor_text_suggestion', models.CharField(blank=True, max_length=255)),
                ('outreach_angle', models.TextField(blank=True, help_text='AI-generated pitch angle')),
                ('status', models.CharField(choices=[('new', 'New'), ('researching', 'Researching'), ('outreaching', 'Outreaching'), ('placed', 'Link Placed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('link_verified', models.BooleanField(default=False)),
                ('link_verified_at', models.DateTimeField(blank=True, null=True)),
                ('actual_link_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlink_opportunities', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Backlink Opportunity',
                'verbose_name_plural': 'Backlink Opportunities',
                'ordering': ['-domain_authority', '-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(choices=[('compose_email', 'Compose Email'), ('move_stage', 'Move Stage'), ('classify_reply', 'Classify Reply'), ('score_lead', 'Score Lead'), ('deal_analyze', 'Analyze Deal'), ('send_email', 'Send Email'), ('pause_deal', 'Pause Deal')], max_length=30)),
                ('reasoning', models.TextField(help_text='AI explanation for the decision')),
                ('action_taken', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='crm.deal')),
            ],
            options={
                'verbose_name': 'AI Decision Log',
                'verbose_name_plural': 'AI Decision Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
