# Generated by Django 4.2.7 on 2026-01-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(help_text='Main website URL')),
                ('description', models.TextField(blank=True)),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254)),
                ('from_name', models.CharField(help_text='Sender display name', max_length=100)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('zoho_account_id', models.CharField(blank=True, max_length=255)),
                ('zoho_refresh_token', models.CharField(blank=True, max_length=1000)),
                ('ai_company_description', models.TextField(blank=True, help_text="Description used in AI prompts (e.g., 'Codeteki is a digital agency...')")),
                ('ai_value_proposition', models.TextField(blank=True, help_text='Value proposition for outreach emails')),
                ('backlink_content_types', models.JSONField(blank=True, default=list, help_text="Types of content for backlink outreach: ['AI tools', 'SEO guides', 'Business directory']")),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#f9cb07', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand-specific template (null = shared across all brands)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='crm.brand'),
        ),
        migrations.AddField(
            model_name='backlinkopportunity',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Which brand this opportunity belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlink_opportunities', to='crm.brand'),
        ),
        migrations.AddField(
            model_name='contact',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Which brand this contact belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.brand'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Which brand this pipeline belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='crm.brand'),
        ),
    ]
