# Generated by Django 4.2.7 on 2026-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_brand_aiprompttemplate_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='zoho_api_domain',
            field=models.CharField(blank=True, default='zoho.com', help_text='Zoho region: zoho.com (US), zoho.com.au (AU), zoho.eu (EU)', max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='zoho_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='zoho_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
