# Generated by Django 4.2.7 on 2026-01-15 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_zoho_fields_to_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='crm/imports/')),
                ('file_name', models.CharField(max_length=255)),
                ('contact_type', models.CharField(choices=[('lead', 'Lead'), ('backlink_target', 'Backlink Target'), ('partner', 'Partner')], default='lead', max_length=20)),
                ('source', models.CharField(default='csv_import', max_length=100)),
                ('create_deals', models.BooleanField(default=False, help_text='Automatically create deals for imported contacts')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_imports', to='crm.brand')),
                ('pipeline', models.ForeignKey(blank=True, help_text='Pipeline for auto-created deals', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pipeline')),
            ],
            options={
                'verbose_name': 'Contact Import',
                'verbose_name_plural': 'Contact Imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
