# Generated by Django 4.2.7 on 2026-01-15 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_contact_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='crm/backlink_imports/')),
                ('file_name', models.CharField(max_length=255)),
                ('source', models.CharField(default='ubersuggest', help_text='Data source: ubersuggest, ahrefs, semrush, moz', max_length=50)),
                ('our_content_url', models.URLField(blank=True, help_text='Your content URL to promote for backlinks')),
                ('min_domain_authority', models.IntegerField(default=0, help_text='Skip domains with DA below this value')),
                ('create_contacts', models.BooleanField(default=False, help_text='Try to create contacts from email columns if available')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlink_imports', to='crm.brand')),
            ],
            options={
                'verbose_name': 'Backlink Import',
                'verbose_name_plural': 'Backlink Imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
