# Generated by Django 4.2.7 on 2026-01-15 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_backlink_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(blank=True, help_text='Recipient name (or leave blank for template)', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, help_text='Recipient email', max_length=254)),
                ('recipient_company', models.CharField(blank=True, max_length=255)),
                ('recipient_website', models.URLField(blank=True)),
                ('email_type', models.CharField(choices=[('sales_intro', 'Sales Introduction'), ('sales_followup', 'Sales Follow-up'), ('backlink_outreach', 'Backlink Outreach'), ('partnership', 'Partnership Proposal'), ('custom', 'Custom')], default='sales_intro', max_length=50)),
                ('your_suggestions', models.TextField(blank=True, help_text='Your ideas, key points, or specific things to mention. AI will incorporate these.')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly & Casual'), ('formal', 'Formal'), ('persuasive', 'Persuasive')], default='professional', max_length=30)),
                ('generated_subject', models.CharField(blank=True, max_length=255)),
                ('generated_body', models.TextField(blank=True)),
                ('final_subject', models.CharField(blank=True, max_length=255)),
                ('final_body', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False, help_text='Save as reusable template')),
                ('template_name', models.CharField(blank=True, help_text='Name for template', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to='crm.brand')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'AI Email Composer',
                'ordering': ['-updated_at'],
            },
        ),
    ]
