# Generated by Django 4.2.7 on 2026-01-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_email_draft_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_count',
            field=models.IntegerField(default=0, help_text='Total emails sent to this contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_unsubscribed',
            field=models.BooleanField(default=False, help_text='Contact has unsubscribed'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, help_text='Last time we emailed this contact', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('unsubscribed', 'Unsubscribed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='unsubscribe_reason',
            field=models.TextField(blank=True, help_text='Why they unsubscribed'),
        ),
        migrations.AddField(
            model_name='contact',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Select existing contact (recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_drafts', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Was this email sent?'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Or enter manually', max_length=254),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Or enter manually', max_length=255),
        ),
    ]
