# Generated by Django 4.2.7 on 2026-01-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_simplify_contact_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Select contacts from list (can select multiple)', related_name='email_drafts', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='manual_emails',
            field=models.TextField(blank=True, help_text='Add emails manually - one per line. Example:\njohn@example.com\njane@company.com'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='sent_count',
            field=models.IntegerField(default=0, help_text='How many emails sent from this draft'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='total_recipients',
            field=models.IntegerField(default=0, help_text='Total recipients (contacts + manual)'),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='contact',
            field=models.ForeignKey(blank=True, help_text="Legacy - use 'contacts' instead", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_drafts_legacy', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
