# Generated by Django 4.2.7 on 2026-01-18 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_bulk_email_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='deals_created',
            field=models.IntegerField(default=0, help_text='Deals created in pipeline'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='Select pipeline - contacts will be added here after first email is sent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pipeline'),
        ),
    ]
