# Generated by Django 4.2.7 on 2026-01-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_add_pipeline_to_emaildraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('backlink', 'Backlink Outreach'), ('partnership', 'Partnership'), ('business', 'Business Listings'), ('deals', 'Deals & Promotions'), ('events', 'Events'), ('realestate', 'Real Estate'), ('classifieds', 'Classifieds')], max_length=20),
        ),
    ]
