# Generated by Django 4.2.7 on 2026-01-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_pipeline_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='email_type',
            field=models.CharField(choices=[('directory_invitation', 'Directory Invitation'), ('listing_benefits', 'Free Listing Benefits'), ('invitation_followup', 'Invitation Follow-up'), ('onboarding_help', 'Onboarding Help'), ('event_invitation', 'Event Organizer Invitation'), ('event_benefits', 'Event Platform Benefits'), ('agent_invitation', 'Agent/Agency Invitation'), ('free_listing', 'Free Property Listing'), ('classifieds_invitation', 'Classifieds Invitation'), ('services_intro', 'Web/AI Services Introduction'), ('seo_services', 'SEO Services Pitch'), ('sales_followup', 'Sales Follow-up'), ('proposal_followup', 'Proposal Follow-up'), ('backlink_pitch', 'Backlink Pitch'), ('guest_post', 'Guest Post Offer'), ('backlink_followup', 'Backlink Follow-up'), ('partnership_intro', 'Partnership Introduction'), ('collaboration', 'Collaboration Proposal'), ('partnership_followup', 'Partnership Follow-up'), ('invitation', 'General Invitation'), ('followup', 'General Follow-up'), ('custom', 'Custom')], default='invitation', max_length=50),
        ),
    ]
