# Generated by Django 4.2.7 on 2026-01-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_update_email_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='unsubscribed_brands',
            field=models.JSONField(blank=True, default=list, help_text="List of brand slugs they've unsubscribed from (e.g., ['codeteki', 'desifirms'])"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_unsubscribed',
            field=models.BooleanField(default=False, help_text='Contact has unsubscribed from ALL brands'),
        ),
    ]
