# Generated by Django 4.2.7 on 2026-01-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_add_unsubscribed_brands_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodetekiContact',
            fields=[
            ],
            options={
                'verbose_name': 'Codeteki Contact',
                'verbose_name_plural': 'Codeteki Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.contact',),
        ),
        migrations.CreateModel(
            name='DesiFirmsContact',
            fields=[
            ],
            options={
                'verbose_name': 'Desi Firms Contact',
                'verbose_name_plural': 'Desi Firms Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.contact',),
        ),
    ]
