# Generated by Django 4.2.7 on 2026-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_codetekicontact_desifirmscontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('unsubscribed', 'Unsubscribed'), ('no_response', 'No Response'), ('not_interested', 'Not Interested'), ('competitor', 'Chose Competitor'), ('budget', 'Budget Issues'), ('timing', 'Bad Timing'), ('invalid_email', 'Invalid Email'), ('other', 'Other')], help_text='Reason for losing the deal', max_length=50),
        ),
    ]
