# Generated by Django 4.2.7 on 2026-01-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_deal_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ai_approach_style',
            field=models.CharField(blank=True, choices=[('problem_solving', 'Problem-Solving (focus on solving their problems)'), ('value_driven', 'Value-Driven (highlight benefits and value)'), ('relationship', 'Relationship-First (build connection before pitching)'), ('direct', 'Direct (clear and to the point)')], default='problem_solving', help_text='AI email writing approach style', max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='ai_business_updates',
            field=models.TextField(blank=True, help_text="Recent updates AI should mention (e.g., 'NEW: Image search, real estate section. Pricing: Free plan, Standard $9.99, Premium $14.99, yearly savings')"),
        ),
        migrations.AddField(
            model_name='brand',
            name='ai_target_context',
            field=models.TextField(blank=True, help_text="Target audience context (e.g., '20+ existing customers need to know about revamp, new features, better pricing')"),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='email_type',
            field=models.CharField(choices=[('directory_invitation', 'Directory Invitation'), ('listing_benefits', 'Free Listing Benefits'), ('invitation_followup', 'Invitation Follow-up'), ('onboarding_help', 'Onboarding Help'), ('event_invitation', 'Event Organizer Invitation'), ('event_benefits', 'Event Platform Benefits'), ('agent_invitation', 'Agent/Agency Invitation'), ('free_listing', 'Free Property Listing'), ('classifieds_invitation', 'Classifieds Invitation'), ('services_intro', 'Web/AI Services Introduction'), ('seo_services', 'SEO Services Pitch'), ('sales_followup', 'Sales Follow-up'), ('proposal_followup', 'Proposal Follow-up'), ('backlink_pitch', 'Backlink Pitch'), ('guest_post', 'Guest Post Offer'), ('backlink_followup', 'Backlink Follow-up'), ('partnership_intro', 'Partnership Introduction'), ('collaboration', 'Collaboration Proposal'), ('partnership_followup', 'Partnership Follow-up'), ('existing_customer_update', 'Existing Customer Update'), ('win_back', 'Win-back Email'), ('feature_announcement', 'New Feature Announcement'), ('pricing_update', 'Pricing Update'), ('invitation', 'General Invitation'), ('followup', 'General Follow-up'), ('custom', 'Custom')], default='invitation', max_length=50),
        ),
    ]
