# Generated by Django 4.2.7 on 2026-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_brand_ai_approach_style_brand_ai_business_updates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, help_text='Leave blank to auto-extract from email/domain', max_length=255),
        ),
    ]
