# Generated by Django 4.2.7 on 2026-01-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_make_contact_name_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('brand', 'email')},
        ),
    ]
