# Generated by Django 4.2.7 on 2026-01-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_contact_email_unique_per_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='send_to_pipeline_contacts',
            field=models.BooleanField(default=False, help_text='Also send to contacts already in a pipeline (normally skipped)'),
        ),
    ]
