# Generated by Django 4.2.7 on 2026-02-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_autopilot_engagement_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_bounced',
            field=models.BooleanField(default=False, help_text='Email address hard-bounced (invalid/non-existent)'),
        ),
    ]
