# Generated by Django 4.2.7 on 2026-02-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_add_contact_bounce_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='soft_bounce_count',
            field=models.IntegerField(default=0, help_text='Number of soft bounces (auto-converts to hard bounce at 3)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='spam_reported',
            field=models.BooleanField(default=False, help_text='Recipient reported email as spam (feedback loop)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='spam_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
