# Generated by Django 4.2.7 on 2026-02-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_add_soft_bounce_and_spam_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='preferred_send_hour',
            field=models.IntegerField(blank=True, help_text='Preferred hour to send emails (0-23), computed from open history', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='re_engagement_attempted',
            field=models.BooleanField(default=False, help_text='Whether this deal has been through automated re-engagement'),
        ),
    ]
