# Generated by Django 4.2.7 on 2026-02-20 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_add_send_optimization_and_reengagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('crawl_data', models.JSONField(default=dict)),
                ('pagespeed_data', models.JSONField(default=dict)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('opportunities', models.JSONField(default=list)),
                ('subscription_trap', models.JSONField(default=dict)),
                ('roadmap', models.JSONField(default=dict)),
                ('tech_stack', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('mobile_score', models.IntegerField(blank=True, null=True)),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_scans', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Prospect Scan',
                'verbose_name_plural': 'Prospect Scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
