# Generated by Django 4.2.7 on 2026-02-20 05:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_add_prospect_scan_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(help_text='Search query used', max_length=200)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(help_text='Location searched', max_length=200)),
                ('radius_km', models.IntegerField(default=5)),
                ('results', models.JSONField(default=list, help_text='Raw API results')),
                ('results_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Search',
                'verbose_name_plural': 'Lead Searches',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, help_text='Business address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Places ID for dedup', max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_rating',
            field=models.FloatField(blank=True, help_text='Google rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='industry',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant / Cafe / Food'), ('trades', 'Trades & Home Services'), ('health_beauty', 'Health & Beauty'), ('retail', 'Retail / Shopping'), ('professional', 'Professional Services'), ('fitness', 'Fitness / Sports'), ('automotive', 'Automotive'), ('education', 'Education / Training'), ('real_estate', 'Real Estate'), ('accommodation', 'Accommodation / Hotels'), ('medical', 'Medical / Healthcare'), ('legal', 'Legal Services'), ('accounting', 'Accounting / Finance'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='email_type',
            field=models.CharField(choices=[('directory_invitation', 'Directory Invitation'), ('listing_benefits', 'Free Listing Benefits'), ('invitation_followup', 'Invitation Follow-up'), ('onboarding_help', 'Onboarding Help'), ('event_invitation', 'Event Organizer Invitation'), ('event_benefits', 'Event Platform Benefits'), ('agent_invitation', 'Agent/Agency Invitation'), ('free_listing', 'Free Property Listing'), ('classifieds_invitation', 'Classifieds Invitation'), ('business_nudge', '🔔 Nudge: List Your Business'), ('business_nudge_2', '🔔 Nudge 2: Business Reminder'), ('realestate_nudge', '🔔 Nudge: Become an Agent'), ('realestate_nudge_2', '🔔 Nudge 2: Agent Reminder'), ('events_nudge', '🔔 Nudge: Post Your Events'), ('events_nudge_2', '🔔 Nudge 2: Events Reminder'), ('services_intro', 'Web/AI Services Introduction'), ('seo_services', 'SEO Services Pitch'), ('sales_followup', 'Sales Follow-up'), ('proposal_followup', 'Proposal Follow-up'), ('prospect_audit_outreach', 'Prospect Audit Outreach'), ('sector_outreach', 'Sector-Specific Outreach'), ('backlink_pitch', 'Backlink Pitch'), ('guest_post', 'Guest Post Offer'), ('backlink_followup', 'Backlink Follow-up'), ('partnership_intro', 'Partnership Introduction'), ('collaboration', 'Collaboration Proposal'), ('partnership_followup', 'Partnership Follow-up'), ('existing_customer_update', 'Existing Customer Update'), ('win_back', 'Win-back Email'), ('feature_announcement', 'New Feature Announcement'), ('pricing_update', 'Pricing Update'), ('invitation', 'General Invitation'), ('followup', 'General Follow-up'), ('custom', 'Custom')], default='invitation', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('brand', 'email'), name='unique_brand_email_when_set'),
        ),
        migrations.AddField(
            model_name='leadsearch',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_searches', to='crm.brand'),
        ),
    ]
