# Generated by Django 4.2.7 on 2026-02-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_add_google_places_fields_and_leadsearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildraft',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Message Draft', 'verbose_name_plural': 'AI Message Composer'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message Log', 'verbose_name_plural': 'Message Logs'},
        ),
        migrations.AddField(
            model_name='brand',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='twilio_phone_number',
            field=models.CharField(blank=True, help_text='E.164 format, e.g. +61400000000', max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='twilio_whatsapp_number',
            field=models.CharField(blank=True, help_text='E.164 format for WhatsApp sender', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_sms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='sms_count',
            field=models.IntegerField(default=0, help_text='Total SMS/WhatsApp messages sent'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sms_opted_out',
            field=models.BooleanField(default=False, help_text='Contact opted out of SMS messages'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sms_opted_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='manual_phones',
            field=models.TextField(blank=True, help_text='Add phones manually - one per line. Example:\n+61412345678\nJohn <+61412345678>'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='delivery_status',
            field=models.CharField(blank=True, help_text='Twilio delivery status', max_length=20),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_sid',
            field=models.CharField(blank=True, help_text='Twilio message SID', max_length=100),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='to_phone',
            field=models.CharField(blank=True, help_text='E.164 phone for SMS/WhatsApp', max_length=30),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='to_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('backlink', 'Backlink Outreach'), ('partnership', 'Partnership'), ('business', 'Business Listings'), ('deals', 'Deals & Promotions'), ('events', 'Events'), ('realestate', 'Real Estate'), ('classifieds', 'Classifieds'), ('registered_users', 'Registered Users (Nudge)'), ('sms_campaign', 'SMS Campaign'), ('whatsapp_campaign', 'WhatsApp Campaign')], max_length=20),
        ),
    ]
