# Generated by Django 4.2.7 on 2026-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_add_twilio_sms_whatsapp_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'SMS/WhatsApp')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'SMS/WhatsApp')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('backlink', 'Backlink Outreach'), ('partnership', 'Partnership'), ('business', 'Business Listings'), ('deals', 'Deals & Promotions'), ('events', 'Events'), ('realestate', 'Real Estate'), ('classifieds', 'Classifieds'), ('registered_users', 'Registered Users (Nudge)'), ('phone_campaign', 'Phone Campaign (SMS/WhatsApp)')], max_length=20),
        ),
    ]
