# Generated by Django 4.2.7 on 2026-02-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_user_registration_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('backlink', 'Backlink Outreach'), ('partnership', 'Partnership'), ('business', 'Business Listings'), ('deals', 'Deals & Promotions'), ('events', 'Events'), ('realestate', 'Real Estate'), ('classifieds', 'Classifieds'), ('registered_users', 'Registered Users (Nudge)'), ('user_registration', 'User Registration'), ('phone_campaign', 'Phone Campaign (SMS/WhatsApp)')], max_length=20),
        ),
    ]
