# Generated by Django 4.2.7 on 2026-02-24 10:50

from django.db import migrations


def create_brandless_pipelines(apps, schema_editor):
    Pipeline = apps.get_model('crm', 'Pipeline')
    PipelineStage = apps.get_model('crm', 'PipelineStage')

    # Sales Pipeline (no brand)
    if not Pipeline.objects.filter(name='Sales Pipeline', brand__isnull=True).exists():
        sales = Pipeline.objects.create(
            name='Sales Pipeline',
            pipeline_type='sales',
            description='',
            is_active=True,
            brand=None,
        )
        for order, (name, days, terminal) in enumerate([
            ('New Lead', 0, False),
            ('Contacted', 3, False),
            ('Interested', 2, False),
            ('Proposal Sent', 3, False),
            ('Negotiating', 5, False),
            ('Won', 0, True),
            ('Lost', 0, True),
        ], start=1):
            PipelineStage.objects.create(
                pipeline=sales, name=name, order=order,
                days_until_followup=days, is_terminal=terminal,
            )

    # Backlink Outreach (no brand)
    if not Pipeline.objects.filter(name='Backlink Outreach', brand__isnull=True).exists():
        backlink = Pipeline.objects.create(
            name='Backlink Outreach',
            pipeline_type='backlink',
            description='',
            is_active=True,
            brand=None,
        )
        for order, (name, days, terminal) in enumerate([
            ('Opportunity Found', 0, False),
            ('Contact Found', 0, False),
            ('Pitch Sent', 5, False),
            ('Follow-up 1', 5, False),
            ('Follow-up 2', 7, False),
            ('Responded', 0, False),
            ('Link Placed', 0, True),
            ('Rejected', 0, True),
        ], start=1):
            PipelineStage.objects.create(
                pipeline=backlink, name=name, order=order,
                days_until_followup=days, is_terminal=terminal,
            )


def reverse(apps, schema_editor):
    Pipeline = apps.get_model('crm', 'Pipeline')
    Pipeline.objects.filter(
        name__in=['Sales Pipeline', 'Backlink Outreach'],
        brand__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_alter_pipeline_pipeline_type'),
    ]

    operations = [
        migrations.RunPython(create_brandless_pipelines, reverse),
    ]
