# Generated by Django 4.2.7 on 2026-02-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_create_brandless_pipelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_whatsapp',
            field=models.BooleanField(blank=True, default=None, help_text='None=unknown, True=confirmed on WhatsApp, False=not on WhatsApp', null=True),
        ),
    ]
