# Generated by Django 4.2.7 on 2026-02-28 04:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_add_has_whatsapp_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('backlink', 'Backlink Outreach'), ('partnership', 'Partnership'), ('business', 'Business Listings'), ('deals', 'Deals & Promotions'), ('events', 'Events'), ('realestate', 'Real Estate'), ('classifieds', 'Classifieds'), ('registered_users', 'Registered Users (Nudge)'), ('user_registration', 'User Registration'), ('phone_campaign', 'Phone Campaign (SMS/WhatsApp)'), ('whatsapp_inquiry', 'WhatsApp Inquiry')], max_length=20),
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='E.164 format', max_length=20, unique=True)),
                ('phase', models.CharField(choices=[('greeting', 'Greeting'), ('discovery', 'Discovery'), ('info_shared', 'Info Shared'), ('engaged', 'Engaged'), ('handoff', 'Handed Off'), ('closed', 'Closed')], default='greeting', max_length=20)),
                ('user_type', models.CharField(choices=[('unknown', 'Unknown'), ('business_owner', 'Business Owner'), ('regular_user', 'Regular User'), ('existing_member', 'Existing Member')], default='unknown', max_length=20)),
                ('ai_active', models.BooleanField(default=True, help_text='AI auto-responds when True')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_company', models.CharField(blank=True, max_length=200)),
                ('detected_intent', models.CharField(blank=True, max_length=200)),
                ('conversation_summary', models.TextField(blank=True)),
                ('message_count', models.IntegerField(default=0)),
                ('ai_message_count', models.IntegerField(default=0)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('handoff_at', models.DateTimeField(blank=True, null=True)),
                ('handoff_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='crm.deal')),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation',
                'verbose_name_plural': 'WhatsApp Conversations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
