# Generated by Django 4.2.7 on 2026-02-28 04:25

from django.db import migrations


def create_whatsapp_inquiry_pipeline(apps, schema_editor):
    """Create WhatsApp Inquiry pipeline with stages for Desi Firms."""
    Brand = apps.get_model('crm', 'Brand')
    Pipeline = apps.get_model('crm', 'Pipeline')
    PipelineStage = apps.get_model('crm', 'PipelineStage')

    brand = Brand.objects.filter(slug='desifirms').first()

    pipeline = Pipeline.objects.create(
        brand=brand,
        name='WhatsApp Inquiry',
        pipeline_type='whatsapp_inquiry',
        description='AI-managed WhatsApp conversations from inbound messages.',
        is_active=True,
    )

    stages = [
        ('New Inquiry', 0, 1, False),
        ('Engaged', 1, 2, False),
        ('Qualified', 2, 3, False),
        ('Handed Off', 3, 1, False),
        ('Converted', 4, 0, True),
        ('Closed', 5, 0, True),
    ]

    for name, order, days, is_terminal in stages:
        PipelineStage.objects.create(
            pipeline=pipeline,
            name=name,
            order=order,
            days_until_followup=days,
            is_terminal=is_terminal,
        )


def reverse_migration(apps, schema_editor):
    Pipeline = apps.get_model('crm', 'Pipeline')
    Pipeline.objects.filter(pipeline_type='whatsapp_inquiry').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_whatsappconversation'),
    ]

    operations = [
        migrations.RunPython(create_whatsapp_inquiry_pipeline, reverse_migration),
    ]
