# Generated by Django 4.2.7 on 2026-03-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_alter_pipeline_pipeline_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'SMS')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'SMS')], default='email', max_length=10),
        ),
    ]
