# Generated by Django 4.2.7 on 2025-11-16 09:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(default='Free AI Tools', max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Tools Section',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Codeteki Digital Services', max_length=160)),
                ('company_description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('abn', models.CharField(blank=True, max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='ROICalculatorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(default='Smart Business Calculator', max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('highlighted_text', models.CharField(max_length=120)),
                ('description', ckeditor.fields.RichTextField()),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ROI Calculator Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(default='Why Choose Codeteki', max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='CheckCircle', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='core.whychoosesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ROICalculatorTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.roicalculatorsection')),
            ],
            options={
                'verbose_name': 'ROI Calculator Tool',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ROICalculatorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=60)),
                ('detail', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.roicalculatorsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('services', 'Services Column'), ('company', 'Company Column'), ('contact', 'Contact Column')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footersection')),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Zap', max_length=40)),
                ('color', models.CharField(default='blue', help_text='Color theme for the tool card', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.aitoolssection')),
            ],
            options={
                'verbose_name': 'AI Tool',
                'ordering': ['order'],
            },
        ),
    ]
