# Generated by Django 4.2.7 on 2025-02-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogpost_ctasection_demoshowcase_navigationmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEODataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('ubersuggest_keywords', 'Ubersuggest Keyword Export')], default='ubersuggest_keywords', max_length=64)),
                ('csv_file', models.FileField(upload_to='seo/uploads/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_ai_run_at', models.DateTimeField(blank=True, null=True)),
                ('insights', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-updated_at'],
                'verbose_name': 'SEO Data Upload',
            },
        ),
        migrations.CreateModel(
            name='SEOKeywordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('seed_keyword', models.CharField(blank=True, max_length=255)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('transactional', 'Transactional'), ('commercial', 'Commercial'), ('navigational', 'Navigational')], default='informational', max_length=32)),
                ('avg_volume', models.PositiveIntegerField(default=0)),
                ('avg_difficulty', models.PositiveSmallIntegerField(default=0)),
                ('keyword_count', models.PositiveIntegerField(default=0)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('summary', models.TextField(blank=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.seodataupload')),
            ],
            options={
                'ordering': ['-priority_score', 'label'],
                'verbose_name': 'SEO Keyword Cluster',
            },
        ),
        migrations.CreateModel(
            name='SEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.PositiveIntegerField(default=0)),
                ('seo_difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paid_difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('keyword_type', models.CharField(choices=[('short_tail', 'Short Tail'), ('mid_tail', 'Mid Tail'), ('long_tail', 'Long Tail')], default='mid_tail', max_length=20)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('transactional', 'Transactional'), ('commercial', 'Commercial'), ('navigational', 'Navigational')], default='informational', max_length=32)),
                ('ranking_url', models.CharField(blank=True, max_length=255)),
                ('trend', models.CharField(blank=True, max_length=120)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='core.seokeywordcluster')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.seodataupload')),
            ],
            options={
                'ordering': ['-priority_score', 'keyword'],
                'verbose_name': 'SEO Keyword',
            },
        ),
        migrations.CreateModel(
            name='AISEORecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('opportunity', 'Opportunity Overview'), ('content_brief', 'Content Brief'), ('metadata', 'Meta Tags'), ('faq', 'FAQ Suggestions')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('error', 'Error')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.seokeywordcluster')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.seokeyword')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.seodataupload')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'AI SEO Recommendation',
            },
        ),
    ]
