# Generated by Django 4.2.7 on 2025-11-17 00:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seodataupload_seokeywordcluster_seokeyword_aisedorecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Codeteki AI Consultant', max_length=120)),
                ('persona_title', models.CharField(default='AI Success Partner', max_length=160)),
                ('intro_message', models.TextField(default="Hi! I'm Codeteki's AI consultant. How can I help you today?")),
                ('fallback_message', models.TextField(default="Thanks for the context. I'll loop in a specialist ASAP so you get a detailed reply.")),
                ('lead_capture_prompt', models.TextField(default='Can I grab your name + email so we can send a tailored plan?')),
                ('success_message', models.TextField(default='Thanks! Our team will reach out with next steps shortly.')),
                ('brand_voice', models.CharField(default='Confident & helpful', max_length=80)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('meeting_link', models.URLField(blank=True)),
                ('accent_color', models.CharField(default='#f9cb07', max_length=12)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='chatbot/')),
                ('quick_replies', models.JSONField(blank=True, default=list)),
                ('escalation_threshold', models.PositiveSmallIntegerField(default=3, help_text='How many exchanges before suggesting human hand-off.')),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_name', models.CharField(blank=True, max_length=120)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_company', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_user_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('keywords', models.TextField(blank=True, help_text='Comma separated terms to assist chat retrieval.')),
                ('persona', models.CharField(choices=[('prospect', 'Prospective Customer'), ('customer', 'Existing Customer'), ('technical', 'Technical Stakeholder')], default='prospect', max_length=40)),
                ('call_to_action', models.CharField(blank=True, max_length=160)),
                ('call_to_action_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='knowledge/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Sparkles', max_length=40)),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_pattern',
            field=models.CharField(default='sunrise-glow', max_length=60),
        ),
        migrations.AddField(
            model_name='herosection',
            name='badge_emoji',
            field=models.CharField(default='🚀', max_length=12),
        ),
        migrations.AddField(
            model_name='herosection',
            name='highlight_gradient_from',
            field=models.CharField(default='#f9cb07', max_length=12),
        ),
        migrations.AddField(
            model_name='herosection',
            name='highlight_gradient_to',
            field=models.CharField(default='#ff6b35', max_length=12),
        ),
        migrations.AddField(
            model_name='herosection',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.CreateModel(
            name='KnowledgeFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.knowledgearticle')),
            ],
            options={
                'verbose_name': 'Knowledge Article FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.knowledgecategory'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('intent', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified')], default='new', max_length=20)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='core.chatconversation')),
            ],
            options={
                'verbose_name': 'Chat Lead',
            },
        ),
    ]
