# Generated by Django 4.2.7 on 2025-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatbotsettings_chatconversation_knowledgearticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='badge',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aitool',
            name='category',
            field=models.CharField(default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='aitool',
            name='credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitool',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aitool',
            name='cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aitool',
            name='emoji',
            field=models.CharField(blank=True, help_text='Optional emoji badge', max_length=8),
        ),
        migrations.AddField(
            model_name='aitool',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aitool',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aitool',
            name='min_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitool',
            name='preview_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aitool',
            name='secondary_cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aitool',
            name='secondary_cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aitool',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('credits', 'Credits'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
