# Generated by Django 4.2.7 on 2025-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aitool_additional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Sparkles', max_length=40)),
                ('accent', models.CharField(default='blue', help_text='Tailwind-friendly color keyword', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Process Step',
                'ordering': ['order'],
            },
        ),
    ]
