# Generated by Django 4.2.7 on 2025-02-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_serviceprocessstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted')], default='new', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'ordering': ['-created_at'],
            },
        ),
    ]
