# Generated by Django 4.2.7 on 2025-02-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoshowcase',
            name='color_class',
            field=models.CharField(default='bg-blue-500', help_text='Tailwind class for icon background', max_length=60),
        ),
        migrations.AddField(
            model_name='demoshowcase',
            name='feature_count',
            field=models.PositiveIntegerField(default=0, help_text='Optional count for additional features'),
        ),
        migrations.AddField(
            model_name='demoshowcase',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line'),
        ),
        migrations.AddField(
            model_name='demoshowcase',
            name='highlight_badge',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='demoshowcase',
            name='icon',
            field=models.CharField(default='Sparkles', help_text='Lucide icon name', max_length=40),
        ),
        migrations.AddField(
            model_name='demoshowcase',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='demoshowcase',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='demos/screenshots/'),
        ),
        migrations.AddField(
            model_name='demoshowcase',
            name='status',
            field=models.CharField(choices=[('live', 'Live Demo'), ('coming_soon', 'Coming Soon'), ('in_development', 'In Development'), ('planning', 'Planning')], default='coming_soon', max_length=20),
        ),
    ]
