# Generated by Django 4.2.7 on 2025-11-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_demoshowcase_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_badge',
            field=models.CharField(default='We respond within 24 hours', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_response_confirmation',
            field=models.CharField(default="We'll contact you within 24 hours to confirm your consultation.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_response_helper',
            field=models.CharField(default='Based on care plan', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_response_label',
            field=models.CharField(default='Average response time', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_response_message',
            field=models.CharField(default='Get a response within 24 hours', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_response_value',
            field=models.CharField(default='< 24 hrs', max_length=60),
        ),
    ]
