# Generated by Django 4.2.7 on 2025-11-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hero_page_and_service_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['page', '-updated_at'], 'verbose_name': 'Hero Section'},
        ),
    ]
