# Generated by Django 4.2.7 on 2025-11-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditissue_competitorprofile_pageaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='article', help_text='Material icon name', max_length=40)),
                ('color', models.CharField(default='blue', help_text='Theme color', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog Post'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Was this content AI-generated?'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from default'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword to optimize for', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (max 160 chars). Leave blank to use excerpt.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 chars). Leave blank to use post title.', max_length=70),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for social sharing (1200x630 recommended)', null=True, upload_to='blog/og/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='secondary_keywords',
            field=models.CharField(blank=True, help_text='Comma separated secondary keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_cluster',
            field=models.ForeignKey(blank=True, help_text='SEO keyword cluster this post targets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.seokeywordcluster'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, help_text='Legacy field - use blog_category instead', max_length=80),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Brief summary for previews (max 320 chars)', max_length=320),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory'),
        ),
    ]
