# Generated by Django 4.2.7 on 2025-11-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_blogcategory_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisReport',
            fields=[
            ],
            options={
                'verbose_name': 'AI Analysis Report',
                'verbose_name_plural': 'AI Analysis Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteaudit',),
        ),
    ]
