# Generated by Django 4.2.7 on 2025-11-27 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aianalysisreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday_friday', 'Monday - Friday'), ('weekends', 'Weekends')], max_length=20)),
                ('hours', models.CharField(help_text="e.g., '9:00 AM - 6:00 PM AEDT' or 'Closed' or 'By appointment'", max_length=100)),
                ('is_closed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['order'],
            },
        ),
    ]
