# Generated by Django 4.2.7 on 2025-11-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_business_hours_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('snapchat', 'Snapchat'), ('threads', 'Threads'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('custom_label', models.CharField(blank=True, help_text="Custom label for 'Other' platform", max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Custom icon name (Lucide icon)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
    ]
