# Generated by Django 4.2.7 on 2025-12-01 20:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_move_social_links_to_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=core.fields.OptimizedImageField(blank=True, null=True, upload_to='blog/', webp_max_size=(2000, 2000)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=core.fields.OptimizedImageField(blank=True, help_text='Image for social sharing (1200x630 recommended)', null=True, upload_to='blog/og/', webp_max_size=(1200, 630)),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='hero_image',
            field=core.fields.OptimizedImageField(blank=True, null=True, upload_to='chatbot/', webp_max_size=(2000, 2000)),
        ),
        migrations.AlterField(
            model_name='demoimage',
            name='image',
            field=core.fields.OptimizedImageField(upload_to='demos/gallery/', webp_max_size=(2000, 2000)),
        ),
        migrations.AlterField(
            model_name='demoshowcase',
            name='client_logo',
            field=core.fields.ThumbnailImageField(blank=True, null=True, upload_to='demos/clients/', webp_max_size=(800, 800), webp_quality=80),
        ),
        migrations.AlterField(
            model_name='demoshowcase',
            name='screenshot',
            field=core.fields.OptimizedImageField(blank=True, null=True, upload_to='demos/screenshots/', webp_max_size=(2000, 2000)),
        ),
        migrations.AlterField(
            model_name='demoshowcase',
            name='thumbnail',
            field=core.fields.ThumbnailImageField(help_text='Main image for the demo', upload_to='demos/', webp_max_size=(800, 800), webp_quality=80),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='logo',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='media',
            field=core.fields.OptimizedImageField(blank=True, null=True, upload_to='hero/', webp_max_size=(2000, 2000)),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='cover_image',
            field=core.fields.OptimizedImageField(blank=True, null=True, upload_to='knowledge/', webp_max_size=(2000, 2000)),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image',
            field=core.fields.OptimizedImageField(blank=True, null=True, upload_to='seo/', webp_max_size=(1200, 630)),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=core.fields.WebPImageField(blank=True, convert_to_webp=False, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=core.fields.WebPImageField(blank=True, help_text='Main logo', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_dark',
            field=core.fields.WebPImageField(blank=True, help_text='Logo for dark backgrounds', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=core.fields.ThumbnailImageField(blank=True, null=True, upload_to='testimonials/', webp_max_size=(800, 800), webp_quality=80),
        ),
    ]
