# Generated by Django 4.2.7 on 2025-12-07 23:13

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceoutcome',
            options={'ordering': ['order'], 'verbose_name': 'Service Feature (Card)', 'verbose_name_plural': 'Service Features (Card)'},
        ),
        migrations.AlterModelOptions(
            name='serviceprocessstep',
            options={'ordering': ['order'], 'verbose_name': 'Global Process Step (Legacy)'},
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, help_text='Full description for the Overview section'),
        ),
        migrations.AddField(
            model_name='service',
            name='gradient_from',
            field=models.CharField(default='purple-600', help_text="Tailwind gradient start e.g. 'purple-600'", max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='gradient_to',
            field=models.CharField(default='indigo-600', help_text="Tailwind gradient end e.g. 'indigo-600'", max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=core.fields.WebPImageField(blank=True, help_text='Hero image for detail page', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Or use external image URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Longer subtitle for hero section', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline shown in hero badge', max_length=160),
        ),
        migrations.AlterField(
            model_name='service',
            name='badge',
            field=models.CharField(blank=True, help_text="Short badge text e.g. 'Enterprise Ready'", max_length=120),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Short description for service cards'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='Sparkles', help_text='Lucide icon name', max_length=40),
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Process Step',
                'verbose_name_plural': 'Service Process Steps',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Feature (Detail Page)',
                'verbose_name_plural': 'Service Features (Detail Page)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='Sparkles', help_text='Lucide icon name', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Capability',
                'verbose_name_plural': 'Service Capabilities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Benefit',
                'verbose_name_plural': 'Service Benefits',
                'ordering': ['order'],
            },
        ),
    ]
