# Generated by Django 4.2.7 on 2025-12-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ubersuggest_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='seodataupload',
            name='error_count',
            field=models.PositiveIntegerField(default=0, help_text='Rows that failed to import'),
        ),
        migrations.AddField(
            model_name='seodataupload',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Link this upload to a specific project/client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_uploads', to='core.seoproject'),
        ),
        migrations.AlterField(
            model_name='seodataupload',
            name='source',
            field=models.CharField(choices=[('Ubersuggest Exports', (('ubersuggest_keywords', 'Keywords Research'), ('ubersuggest_competitors', 'Competitors List'), ('ubersuggest_competitor_keywords', 'Competitor Keywords'), ('ubersuggest_backlinks', 'Backlinks Export'), ('ubersuggest_top_pages', 'Top Pages by Traffic'), ('ubersuggest_content_ideas', 'Content Ideas'), ('ubersuggest_site_audit', 'Site Audit Issues'), ('ubersuggest_keyword_gaps', 'Keyword Gap Analysis'), ('ubersuggest_rankings', 'Rank Tracking Export')))], default='ubersuggest_keywords', max_length=64),
        ),
        migrations.AlterField(
            model_name='seodataupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
