# Generated by Django 4.2.7 on 2025-12-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_seo_upload_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='blog_post',
            field=models.OneToOneField(blank=True, help_text='Link to a blog post for auto-URL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='core.blogpost'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='custom_url',
            field=models.CharField(blank=True, help_text='For dynamic pages like /services/ai-chatbots or /blog/my-post', max_length=255),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='service',
            field=models.OneToOneField(blank=True, help_text='Link to a service for auto-URL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='core.service'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, help_text='AI recommendation that generated this SEO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aiseorecommendation'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='target_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword being targeted', max_length=255),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('services', 'Services Page'), ('ai-tools', 'AI Tools Page'), ('demos', 'Demos Page'), ('faq', 'FAQ Page'), ('contact', 'Contact Page'), ('about', 'About Page'), ('pricing', 'Pricing Page'), ('custom', 'Custom URL')], default='custom', max_length=50),
        ),
    ]
