# Generated by Django 4.2.7 on 2025-12-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_page_seo_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('services', 'Services Page'), ('ai-tools', 'AI Tools Page'), ('demos', 'Demos Page'), ('faq', 'FAQ Page'), ('contact', 'Contact Page'), ('custom', 'Custom URL')], default='custom', max_length=50),
        ),
    ]
