# Generated by Django 4.2.7 on 2025-12-09 08:50

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_pageseo_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=core.fields.OptimizedImageField(blank=True, help_text="Default image for social sharing (1200x630). Used when pages don't have their own OG image.", null=True, upload_to='site/', webp_max_size=(1200, 630)),
        ),
    ]
