# Generated by Django 4.2.7 on 2025-12-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_default_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seocompetitor',
            name='backlinks_count',
            field=models.IntegerField(blank=True, help_text='How many backlinks they have', null=True),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='domain',
            field=models.CharField(help_text="Competitor's domain WITHOUT https://. Example: 'hrblock.com.au'", max_length=255),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='domain_score',
            field=models.IntegerField(blank=True, help_text='Their Domain Authority (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Check this for your main competitor. You'll see them highlighted in reports."),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='monthly_traffic',
            field=models.IntegerField(blank=True, help_text='Their estimated monthly traffic', null=True),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='name',
            field=models.CharField(blank=True, help_text="Competitor's business name. Example: 'H&R Block Australia'", max_length=200),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='notes',
            field=models.TextField(blank=True, help_text="Notes about this competitor. Example: 'They rank #1 for accounting melbourne'"),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='organic_keywords',
            field=models.IntegerField(blank=True, help_text='How many keywords they rank for', null=True),
        ),
        migrations.AlterField(
            model_name='seodataupload',
            name='csv_file',
            field=models.FileField(help_text='Upload the CSV file exported from Ubersuggest → Keywords → Export', upload_to='seo/uploads/'),
        ),
        migrations.AlterField(
            model_name='seodataupload',
            name='name',
            field=models.CharField(help_text="Descriptive name. Example: 'Desifirms Keywords Dec 2025' or 'Codeteki Competitor Analysis'", max_length=255),
        ),
        migrations.AlterField(
            model_name='seodataupload',
            name='notes',
            field=models.TextField(blank=True, help_text="Optional notes. Example: 'Focus on accounting keywords' or 'Competitor: XYZ Accounting'"),
        ),
        migrations.AlterField(
            model_name='seodataupload',
            name='project',
            field=models.ForeignKey(blank=True, help_text="Optional: Link to a project (e.g., 'Desifirms' or 'Client ABC'). Leave blank if just testing.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_uploads', to='core.seoproject'),
        ),
        migrations.AlterField(
            model_name='seodataupload',
            name='source',
            field=models.CharField(choices=[('Ubersuggest Exports', (('ubersuggest_keywords', 'Keywords Research'), ('ubersuggest_competitors', 'Competitors List'), ('ubersuggest_competitor_keywords', 'Competitor Keywords'), ('ubersuggest_backlinks', 'Backlinks Export'), ('ubersuggest_top_pages', 'Top Pages by Traffic'), ('ubersuggest_content_ideas', 'Content Ideas'), ('ubersuggest_site_audit', 'Site Audit Issues'), ('ubersuggest_keyword_gaps', 'Keyword Gap Analysis'), ('ubersuggest_rankings', 'Rank Tracking Export')))], default='ubersuggest_keywords', help_text="What type of Ubersuggest export is this? 'Keywords Research' is most common.", max_length=64),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='backlinks_count',
            field=models.IntegerField(blank=True, help_text='Total links from other websites pointing to this domain', null=True),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='domain',
            field=models.CharField(help_text="Website domain WITHOUT https://. Examples: 'codeteki.au', 'desifirms.com.au'", max_length=255),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='domain_score',
            field=models.IntegerField(blank=True, help_text='Domain Authority from Ubersuggest (0-100). Higher = stronger domain.', null=True),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='monthly_traffic',
            field=models.IntegerField(blank=True, help_text='Estimated monthly visitors from organic search', null=True),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='name',
            field=models.CharField(help_text="Client or project name. Examples: 'Codeteki', 'Desifirms', 'Client ABC'", max_length=200),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='notes',
            field=models.TextField(blank=True, help_text="Any notes about this project. Example: 'Focus on accounting services keywords'"),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='organic_keywords',
            field=models.IntegerField(blank=True, help_text='Total keywords this domain ranks for in Google', null=True),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='target_country',
            field=models.CharField(default='AU', help_text='2-letter country code. AU=Australia, US=USA, UK=United Kingdom', max_length=10),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='target_keywords',
            field=models.IntegerField(blank=True, help_text='Target number of keywords to rank for. Example: 500', null=True),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='target_language',
            field=models.CharField(default='en', help_text='2-letter language code. en=English, es=Spanish', max_length=10),
        ),
        migrations.AlterField(
            model_name='seoproject',
            name='target_traffic',
            field=models.IntegerField(blank=True, help_text='Your goal for monthly traffic. Example: 10000', null=True),
        ),
    ]
