# Generated by Django 4.2.7 on 2025-12-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_seocompetitor_backlinks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaudit',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for background audit', max_length=255, null=True),
        ),
    ]
