# Generated by Django 4.2.7 on 2026-01-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Descriptive name for this job (e.g., 'AI Website Builders - Jan 2025')", max_length=255)),
                ('source_type', models.CharField(choices=[('auto_detect', '🔍 Auto-Detect CSV Type'), ('csv_prompts', '💡 Prompt Ideas CSV'), ('csv_keywords', '🔑 Keywords CSV'), ('csv_competitors', '🏆 Competitor Keywords'), ('csv_backlinks', '🔗 Backlink Opportunities'), ('manual_topics', '✏️ Manual Topics')], default='auto_detect', help_text="Type of data source. 'Auto-Detect' will analyze the CSV structure.", max_length=50)),
                ('csv_file', models.FileField(blank=True, help_text='Upload CSV file from Ubersuggest, competitor analysis, or any keyword data', null=True, upload_to='blog/generation/')),
                ('manual_topics', models.TextField(blank=True, help_text="Enter topics manually, one per line. Used when source is 'Manual Topics'")),
                ('target_word_count', models.PositiveIntegerField(default=1500, help_text='Target word count for each blog post (1000-2500 recommended)')),
                ('writing_style', models.CharField(choices=[('conversational', 'Conversational (Recommended)'), ('professional', 'Professional'), ('technical', 'Technical/Expert'), ('casual', 'Casual/Friendly')], default='conversational', help_text='Writing style affects tone and structure', max_length=50)),
                ('include_services', models.BooleanField(default=True, help_text='Naturally mention relevant Codeteki services in the content')),
                ('auto_publish', models.BooleanField(default=False, help_text='Automatically publish generated posts (otherwise saved as drafts)')),
                ('max_posts', models.PositiveIntegerField(default=5, help_text='Maximum number of posts to generate from this job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning Data'), ('generating', 'Generating Content'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detected_type', models.CharField(blank=True, help_text='Auto-detected CSV type after scanning', max_length=50)),
                ('scan_results', models.JSONField(blank=True, default=dict, help_text='Detected columns, sample data, and extracted topics')),
                ('selected_topics', models.JSONField(blank=True, default=list, help_text='Topics selected for blog generation')),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('target_category', models.ForeignKey(blank=True, help_text='Category for generated blog posts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Generation Job',
                'verbose_name_plural': 'Blog Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
