# Generated by Django 4.2.7 on 2026-03-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='relevance_tags',
            field=models.JSONField(blank=True, default=list, help_text="Keywords for recommendation matching, e.g. ['restaurant', 'booking', 'leads']"),
        ),
    ]
